logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
excluded-patches = ""
included-patches = ""
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-arch = "both"

[Music-Extended]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "both"

[YouTube-Extended]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
included-patches = "'Add splash animation' 'Alternative thumbnails' 'Bypass ambient mode restrictions' 'Change homepage' 'Custom double tap length' 'Custom package name' 'Custom playback speed' 'Custom seekbar color' 'Default playback speed' 'Default video quality' 'Disable QUIC protocol' 'Disable Shorts on startup' 'Disable auto captions' 'Disable haptic feedback' 'Disable hdr video' 'Disable landscape mode' 'Disable pip notification' 'Enable compact controls overlay' 'Enable debug logging' 'Enable external browser' 'Enable minimized playback' 'Enable new comment popup panels' 'Enable new splash animation' 'Enable new thumbnail preview' 'Enable old quality layout' 'Enable open links directly' 'Enable seekbar tapping' 'Enable tablet mini player' 'Enable tablet navigation bar' 'Enable time stamps speed' 'Enable wide search bar' 'Force OPUS codec' 'Force VP9 codec' 'Force hide player button background' 'Force premium heading' 'Header switch' 'Hide account menu' 'Hide auto player popup panels' 'Hide autoplay button' 'Hide autoplay preview' 'Hide button container' 'Hide captions button' 'Hide cast button' 'Hide category bar' 'Hide channel avatar section' 'Hide channel watermark' 'Hide collapse button' 'Hide comment component' 'Hide crowdfunding box' 'Hide description components' 'Hide double tap overlay filter' 'Hide end screen cards' 'Hide end screen overlay' 'Hide feed flyout panel' 'Hide filmstrip overlay' 'Hide floating microphone' 'Hide fullscreen panels' 'Hide general ads' 'Hide handle' 'Hide info cards' 'Hide latest videos button' 'Hide layout components' 'Hide load more button' 'Hide mix playlists' 'Hide music button' 'Hide navigation buttons' 'Hide navigation label' 'Hide player button background' 'Hide player flyout panel' 'Hide player overlay filter' 'Hide previous next button' 'Hide quick actions' 'Hide seek message' 'Hide seekbar' 'Hide shorts components' 'Hide snack bar' 'Hide speed overlay' 'Hide suggested actions' 'Hide suggested video overlay' 'Hide suggestions shelf' 'Hide time stamp' 'Hide tooltip content' 'Hide trending searches' 'Hide video ads' 'Higher fullscreen seekbar height' 'Language switch' 'Layout switch' 'MaterialYou' 'MicroG support' 'Optimize resource' 'Overlay buttons' 'Return YouTube Dislike' 'Settings' 'SponsorBlock' 'Spoof app version' 'Spoof player parameters' 'Swipe controls' 'Theme' 'Translations'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Twitter]
build-mode = "apk"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[Twitch]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

[TikTok]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Reddit]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Lightroom]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
apkmirror-arch = "arm64-v8a + x86_64"

[Messenger]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "arm64-v8a"

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Citra]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/citra-emulator/citra-emulator/"
apkmirror-arch = "arm64-v8a"

[Backdrops]
enabled = false
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[WarnWetter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"

[Windyapp]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[TickTick]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/appest-inc/ticktick-to-do-list-with-reminder-day-planner/"
apkmirror-arch = "arm64-v8a"

[Tasker]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/joaomgcd/tasker/"

[Photomath]
enabled = false
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"
